metrics:
  hosts:
    metrics-01.devnet.shimmer.iota.cafe:

supports:
  hosts:
    analysisentry-01.devnet.shimmer.iota.cafe:
      entryNodeSeed: "{{ ANALYSISSENTRY_01_ENTRYNODE_SEED }}"

goshimmers:
  hosts:
    bootstrap-01.devnet.shimmer.iota.cafe:
      seed: "{{ BOOTSTRAP_01_SEED }}"
      bootstrap: true
    vanilla-01.devnet.shimmer.iota.cafe:
      seed: "{{ VANILLA_01_SEED }}"
    drng-01.devnet.shimmer.iota.cafe:
      seed: "{{ DRNG_01_SEED }}"
    drng-02.devnet.shimmer.iota.cafe:
      seed: "{{ DRNG_02_SEED }}"
    drng-03.devnet.shimmer.iota.cafe:
      seed: "{{ DRNG_03_SEED }}"
    drng-04.devnet.shimmer.iota.cafe:
      seed: "{{ DRNG_04_SEED }}"
    drng-05.devnet.shimmer.iota.cafe:
      seed: "{{ DRNG_05_SEED }}"
    faucet-01.devnet.shimmer.iota.cafe:
      seed: "{{ FAUCET_01_SEED }}"
      faucet: true
      faucetSeed: "{{ FAUCET_01_FAUCET_SEED }}"

drands:
  hosts:
    drand-01.devnet.shimmer.iota.cafe: