metrics:
  hosts:
    metrics-01.devnet.shimmer.iota.cafe:

supports:
  hosts:
    analysisentry-01.devnet.shimmer.iota.cafe:
      entryNodeSeed: "{{ lookup('env', 'ANALYSISSENTRY_01_ENTRYNODE_SEED') }}"

goshimmers:
  hosts:
    bootstrap-01.devnet.shimmer.iota.cafe:
      seed: "{{ lookup('env', 'BOOTSTRAP_01_SEED') }}"
      bootstrap: true
    vanilla-01.devnet.shimmer.iota.cafe:
      seed: "{{ lookup('env', 'VANILLA_01_SEED') }}"
    drng-01.devnet.shimmer.iota.cafe:
      seed: "{{ lookup('env', 'DRNG_01_SEED') }}"
    drng-02.devnet.shimmer.iota.cafe:
      seed: "{{ lookup('env', 'DRNG_02_SEED') }}"
    drng-03.devnet.shimmer.iota.cafe:
      seed: "{{ lookup('env', 'DRNG_03_SEED') }}"
    drng-04.devnet.shimmer.iota.cafe:
      seed: "{{ lookup('env', 'DRNG_04_SEED') }}"
    drng-05.devnet.shimmer.iota.cafe:
      seed: "{{ lookup('env', 'DRNG_05_SEED') }}"
    faucet-01.devnet.shimmer.iota.cafe:
      seed: "{{ lookup('env', 'FAUCET_01_SEED') }}"
      faucet: true
      faucetSeed: "{{ lookup('env', 'FAUCET_01_FAUCET_SEED') }}"

drands:
  hosts:
    drand-01.devnet.shimmer.iota.cafe: