scrape_configs:
    - job_name: analysis_server
      scrape_interval: 5s
      static_configs:
      - targets:
        - analysisentry-01.pre-devnet.shimmer.iota.cafe:9312
        - bootstrap-01.pre-devnet.shimmer.iota.cafe:9312
        - vanilla-01.pre-devnet.shimmer.iota.cafe:9312
        - drng-01.pre-devnet.shimmer.iota.cafe:9312
        - drng-02.pre-devnet.shimmer.iota.cafe:9312
        - drng-03.pre-devnet.shimmer.iota.cafe:9312
        - drng-04.pre-devnet.shimmer.iota.cafe:9312
        - drng-05.pre-devnet.shimmer.iota.cafe:9312
        - faucet-01.pre-devnet.shimmer.iota.cafe:9312
